[Settings]
ID = "snapjay.com"

[build]
  base    = "/"
  publish = "dist"
  command = "npm run build"
  ignore  = "git diff --quiet HEAD^ HEAD -- . ':!.photos' ':!.old.panels' ':!.oldv2.2.backup' ':!.vscode'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[edge_functions]]
  path = "/*"
  function = "geo-block"
